### ISSUE TITLE
Which-key causes WinShift swap to prompt "Press Enter or type command to continue"

### ISSUE THREAD

**Issue by petertriho** [sindrets/winshift.nvim#8] opened 2021-11-14 14:39 UTC
![image](https://user-images.githubusercontent.com/7420227/141685743-26ce7ab2-da4d-40b4-95c9-7256d51ec627.png)

Prompts to "Press Enter or type command to continue" after selecting a window (in this screen shot I pressed "B")

Latest commit (https://github.com/sindrets/winshift.nvim/commit/08e314f3e5babc6eb3e823d2caa27bd2983a1204) is causing this issue for me

**Comment by sindrets** [comment] 2021-11-14 15:02
Any errors / information in `:messages`?

**Comment by petertriho** [comment] 2021-11-14 15:26
Nope, empty. I tried the previous commit (b5f5ac0b25f9722eaa92f0d563194c72a5dde0d6) and I do not get the prompt

**Comment by sindrets** [comment] 2021-11-14 15:57
That is very mysterious. I didn't change anything in the latest commit that should trigger that prompt.

The window swapping completes as usual after pressing enter?

I'm gonna need a minimal config that makes this reproducible, because I'm not seeing this behavior on my end. I left a template for a minimal config in a comment in #7 that you can use.

**Comment by petertriho** [comment] 2021-11-15 04:02
I tried the mini.lua config, and it doesn't have the same issue. I'll investigate further

**Comment by petertriho** [comment] 2021-11-15 05:01
Found the culprit. There's something going on with `folke/whichkey.nvim` plugin. If the `which-key` ever pops up, it causes the "Press enter or type command to continue" issue. The problem was always there (tested again with other commits), I just never noticed due to fast input. 

I've attached the modified `mini.lua` with `which-key`.

<details>
<summary>mini.lua</summary>

```lua
-- mini.lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'sindrets/winshift.nvim',
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      'folke/which-key.nvim'
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  vim.opt.nu = true
  vim.opt.termguicolors = true
  vim.opt.splitbelow = true
  vim.opt.splitright = true
  vim.cmd("colorscheme slate")
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing dependencies...")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]

require("which-key").setup()

local set_keymap = vim.api.nvim_set_keymap
local opts = { noremap = true, silent = true }
set_keymap("n", "<C-w><C-m>", "<CMD>WinShift swap<CR>", opts)
set_keymap("n", "<C-w>m", "<CMD>WinShift swap<CR>", opts)
```

</details>

To reproduce:
1. `<C-w>`
2. Wait a half a second for which-key to popup
3. ` v `
4. `<C-w>s`
5. `<C-w>m`
6. `a` > `Enter`


EDIT: With further investigation, it seems like this happens with all popups

**Comment by sindrets** [comment] 2021-11-15 10:14
Thanks for doing the investigation and the minimal config! Should be fixed now.

**Closed as completed** 2021-11-15 10:13 UTC

**Comment by petertriho** [comment] 2021-11-15 10:17
Thanks! Just tested and it's working as intended now 😃
